name: Elixir CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-test:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    container:
      image: elixir:1.13.2-alpine
    services:
      ravendb:
        image: ravendb/ravendb
        ports:
          - 8080:8080
        env:
          RAVEN_Setup_Mode: 'None'
          RAVEN_License_Eula_Accepted: 'true'
          RAVEN_Security_UnsecuredAccessAllowed: 'PublicNetwork'
    steps:
      - uses: actions/checkout@v2
      - name: Cache build, deps
        uses: actions/cache@v2
        id: mix-deps
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-01-build-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-01-build-${{ hashFiles('mix.lock') }}
            ${{ runner.os }}-01-build-
      - name: Cache build, deps
        uses: actions/cache@v2
        id: mix-dialyzer
        with:
          path: priv/plts
          key: ${{ runner.os }}-01-dialyzer-${{ hashFiles('priv/plts/dialyzer.plt.hash') }}
          restore-keys: |
            ${{ runner.os }}-01-dialyzer-${{ hashFiles('priv/plts/dialyzer.plt.hash') }}
            ${{ runner.os }}-01-dialyzer-
      - name: Install Git/Curl/GNU Tar
        run: apk add --no-cache git curl tar
      - name: Instal Mix and Rebar
        run: mix local.hex --force && mix local.rebar --force
      - name: Install dependencies
        run: mix deps.get
      - name: Run Dialyzer
        run: mix dialyzer
      - name: Run tests
        env:
          RAVENDB_URL: 'http://ravendb:8080'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mix coveralls.github
