name: Elixir CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-test:
    name: Build and test
    runs-on: ubuntu-latest
    container: elixir:1.13.2-alpine
    services:
      ravendb:
        image: ravendb/ravendb:5.3-ubuntu-latest
        env:
          RAVEN_Setup_Mode: None
          RAVEN_Security_UnsecuredAccessAllowed: PrivateNetwork
        ports:
          - 8080:8080
    steps:
      - uses: actions/checkout@v2
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install Git
        run: apk add --no-cache git
      - name: Install dependencies
        run: mix local.hex --force && mix deps.get
      - name: Run tests
        env:
          RAVENDB_URL: http://localhost:${{ job.services.ravendb.ports['8080'] }}
        run: mix test
